### ISSUE TITLE
versions.py

### ISSUE THREAD

**Issue by awhitbeck** [elliot-hughes/hcal_teststand_scripts#1]
version.py does not work with the July3_2015 branch... which as write this message is the same as master....

@Teststandees/citizens

**Comment by elliot-hughes** [comment]
That's annoying. Can I use the system to troubleshoot this right now?

Also, I think once the scripts are all back in working order, we can
start working on other branches and releases. But until then, it seems
sort of pointless.

**Comment by awhitbeck** [comment]
yes, also I am not sure that I can just reply via email.

As far as branches, I can't really report an issue if the branch is
constantly changing.  Branch are cheap so don't feel bad making a new one
every once in a while.

**Comment by elliot-hughes** [comment]
I updated the `master` branch so that `versions.py` works. The most basic problem I introduced was switching the `ngccm.send_commands` function from accepting the ngCCM server port number as the argument to a `teststand` object. I think this switch is now mostly implemented.
