### ISSUE TITLE
select channels by QIE card unique ID

### ISSUE THREAD

**Issue by awhitbeck** [elliot-hughes/hcal_teststand_scripts#11]
This was discussed earlier, but just to jot down some notes... 

We need a function (in the uHTR module???) which takes the QIE card's unique ID, find the relevant QIE channels and links from the json map and returns them.  Initially, we were saying that we would have an option to still run over all of the cards, but I think we should drop this for now and always require a specific card be accepted.

**Comment by elliot-hughes** [comment]
I think the [`ts.uhtr_from_qie`](https://github.com/Teststandees/hcal_teststand_scripts/blob/master/hcal_teststand/hcal_teststand.py#L128) method does this:

```
[elhughes@pc-e1a02-32-01 hcal_teststand_scripts]$ python -i example.py 

You've just run a script that's a skeleton for making your own script.
>> The teststand you're using is named 904.
>> The crate and QIE card organization for the teststand is below:
{1: [2, 10]}
>>> ts.uhtr_from_qie(qie_id="0x8D000000 0xAA24DA70")
{11: [12, 13, 14, 15, 16, 17]}
```

This is the uHTR slot number followed by the relevant links. It doesn't return channel information at the moment.

**Comment by awhitbeck** [comment]
awesome!!!! This is a great start.  At least we'll know we're testing the right board!
