### ISSUE TITLE
pedestalHistos broken

### ISSUE THREAD

**Issue by awhitbeck** [elliot-hughes/hcal_teststand_scripts#12]
it looks like there was an update which broke the pedestalHistos code (note I also had to change the hard coded uhtr slot number from 12 to 11... need to fix this):

End Of File (EOF) in read_nonblocking(). Exception style platform.
<pexpect.spawn object at 0x205c850>
version: 2.3 ($Revision: 399 $)
command: /nfshome0/hcalsw/bin/ngFEC.exe
args: ['/nfshome0/hcalsw/bin/ngFEC.exe', '-z', '-c', '-p', '4242']
searcher: searcher_re:
    0: re.compile("get\ HF1-1-UniqueID #((\s|E).*)
")
buffer (last 100 chars): 
before (last 100 chars): umped) LD_LIBRARY_PATH=/nfshome0/hcalpro/ngFEC:$LD_LIBRARY_PATH /nfshome0/hcalpro/ngFEC/ngccm "$@"

after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: 139
flag_eof: True
pid: 30920
child_fd: 3
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
Traceback (most recent call last):
  File "pedestalHistos.py", line 31, in <module>
    links = uhtr.get_links(ts,11)
  File "/cms904nfshome0/nfshome0/whitbeck/hcal_teststand_scripts/hcal_teststand/uhtr.py", line 360, in get_links
    is_set = qie.set_unique_id_all(ts)
  File "/cms904nfshome0/nfshome0/whitbeck/hcal_teststand_scripts/hcal_teststand/qie.py", line 268, in set_unique_id_all
    is_set.append(set_unique_id(ts, crate, slot))       # Set the QIE card's unique ID into the correct IGLOO registers.
  File "/cms904nfshome0/nfshome0/whitbeck/hcal_teststand_scripts/hcal_teststand/qie.py", line 254, in set_unique_id
    unique_id = get_unique_id(ts, crate, slot)
  File "/cms904nfshome0/nfshome0/whitbeck/hcal_teststand_scripts/hcal_teststand/qie.py", line 130, in get_unique_id
    result = ngccm_output["output"][0]["result"]
IndexError: list index out of range

**Comment by elliot-hughes** [comment]
I think this happened because the teststand wasn't set up properly (backplane power was bad). After I  ran `ts_setup.py`, this script worked. I'll leave this issue open, though, to remind us to add a more useful error message.

**Comment by awhitbeck** [comment]
that is strange because I had already ran the ts_setup script.  I guess I should have rant the status script.

**Comment by awhitbeck** [comment]
I don't know what the resolution here was, but its no longer an issue....
