### ISSUE TITLE
plot script for monitoring system

### ISSUE THREAD

**Issue by yw5mj** [elliot-hughes/hcal_teststand_scripts#16]
To do:
1. Send email asking about the current "ERROR!!" output
2. Add voltage and current vs time plots
3. Add orbit rate plots
4. Run ts_setup
5. QIE reset count plot (Tote can you tell me what registers I should read to get the reset count information? Thanks!)

**Comment by awhitbeck** [comment]
one clarification on point 4.  What I meant in my notes was that we should reset the counters in the DTC menu in the ts_setup script.   We shouldn't run this every time the monitoring scripts are used.

**Comment by yw5mj** [comment]
Yes I know what you mean. Sorry for my confusing description in the issue.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From: Andrew WhitbeckSent: Friday, August 21, 2015 11:52 AMTo: Teststandees/hcal_teststand_scriptsReply To: Teststandees/hcal_teststand_scriptsCc: Yanchu WangSubject: Re: [hcal_teststand_scripts] plot script for monitoring system (#16)one clarification on point 4.  What I meant in my notes was that we should reset the counters in the DTC menu in the ts_setup script.   We shouldn't run this every time the monitoring scripts are used.

—Reply to this email directly or view it on GitHub.
