### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by elliot-hughes** [elliot-hughes/hcal_teststand_scripts#6]
We need to combine `log_teststand.py` and `ts_status.py` to make useful logs at 904 like we were doing at CHARM. This shouldn't be too hard.

**Comment by elliot-hughes** [comment]
Thanks to Yanchu, we are currently logging the teststand with [`log_teststand.py`](https://github.com/Teststandees/hcal_teststand_scripts/blob/master/log_teststand.py). But we have some work still to do:
- Output to a database instead of to text files.
- Include information for each physical component (version info, for example), like [`ts_status.py`](https://github.com/Teststandees/hcal_teststand_scripts/blob/master/ts_status.py) does.
- _There are a few more details I'm forgetting._

**Comment by awhitbeck** [comment]
To keep this up to date:
- save output to a root file... try to open existing root file, append the tree, and close root file.  Lets ignore the database for now.
