### ISSUE TITLE
Setup Script

### ISSUE THREAD

**Issue by elliot-hughes** [elliot-hughes/hcal_teststand_scripts#8]
We need to include commands in the QIE card `setup` that set default registers for the QIE10s and IGLOO2s. This way, we don't have to powercycle the crate to know that things are set up in the right way. Here is a list:
- Set QIE10 registers to the default value.
- [Turn off link test mode.](https://github.com/Teststandees/hcal_teststand_scripts/blob/master/hcal_teststand/hcal_teststand.py#L324)

**Comment by awhitbeck** [comment]
One more thing on this to-do list should be to change the default orbit delay in the uHTR link initialization to be 55.  This is a much much much (!) more stable configuration.
