### ISSUE TITLE
AMC13 config file

### ISSUE THREAD

**Issue by yw5mj** [elliot-hughes/hcal_teststand_scripts#9]
We will probably have to change things due to [this](http://cmsonline.cern.ch/portal/page/portal/CMS%20online%20system/Elog?_piref815_429145_815_429142_429142.strutsAction=%2FviewMessageDetails.do%3FmsgId%3D868463).

**Comment by elliot-hughes** [comment]
All that needed to be changed were the [904 AMC13 IP addresses](https://github.com/Teststandees/hcal_teststand_scripts/blob/master/configuration/teststands.txt#L44).
